server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #连接池类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 961110
  cloud:
    zookeeper:
      connect-string: 192.168.175.130:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wlk.springcloud.entity

